### ISSUE TITLE
EPANET-UI MTP4R1 fails to start on Win 10

### ISSUE THREAD

**Issue by petew0309** [USEPA/SWMM-EPANET_User_Interface#287]
Hello,

A cmd window is displayed briefly and then the program fails to start.

Client machine in question is running Windows 10 Enterprise, 64-bit (build 17134)

I have the program running fine on my machine; Windows 10 Enterprise, 64-bit (build 16299)

Following output when running from cmd line:

C:\Program Files\EPANET-UI>EPANET-UI.exe
Traceback (most recent call last):
  File "src\ui\EPANET\frmMainEPANET.py", line 13, in <module>
  File "c:\users\tong~1.zha\appdata\local\temp\pip-build-9xst00\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ui\frmMain.py", line 29, in <module>
  File "c:\users\tong~1.zha\appdata\local\temp\pip-build-9xst00\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ui\frmTranslateCoordinates.py", line 7, in <module>
  File "c:\users\tong~1.zha\appdata\local\temp\pip-build-9xst00\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ui\selectCrsDlg.py", line 24, in <module>
  File "c:\users\tong~1.zha\appdata\local\temp\pip-build-9xst00\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "qgis\__init__.py", line 36, in <module>
  File "c:\users\tong~1.zha\appdata\local\temp\pip-build-9xst00\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "qgis\core\__init__.py", line 3, in <module>
  File "c:\users\tong~1.zha\appdata\local\temp\pip-build-9xst00\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
ImportError: DLL load failed: The specified module could not be found.
Failed to execute script frmMainEPANET

Any help would be greatly appreciated.

Many thanks,

Pete

**Comment by petew0309** [comment]
@TongZhai 

Thanks for the reply - the user is out of office at the moment, but I'll get this installed and tested ASAP.

Thanks,

Pete

**Comment by TongZhai** [comment]
new windows 10 [release](https://github.com/USEPA/SWMM-EPANET_User_Interface/releases/tag/MTP5r0) were released and tested well
