### ISSUE TITLE
View transect causes crash

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#334]
To reproduce:

- Open extran8b.inp (see https://github.com/USEPA/SWMM-EPANET_User_Interface/blob/master/test/core/swmm/Examples/extran8/extran8b.inp)
- Click Transects in the Project Explorer
- Select Transect 91 and click the edit hand
- Click View

The program crashes with SWMM-UI.exe has stopped working.  Here is the stack trace:
```
Traceback (most recent call last):
  File "frmTransect.py", line 136, in btnView_Clicked
  File "ui\frmPlotViewer.py", line 74, in __init__
  File "ui\frmPlotViewer.py", line 100, in do_plot
  File "ui\frmPlotViewer.py", line 173, in set_xy_data
  File "ui\frmPlotViewer.py", line 134, in setData
  File "site-packages\matplotlib\axes\_base.py", line 2051, in relim
  File "site-packages\matplotlib\axes\_base.py", line 1907, in _update_line_limits
  File "site-packages\matplotlib\lines.py", line 945, in get_path
  File "site-packages\matplotlib\lines.py", line 639, in recache
  File "site-packages\matplotlib\artist.py", line 186, in convert_xunits
  File "site-packages\matplotlib\axis.py", line 1530, in convert_units
  File "site-packages\matplotlib\category.py", line 53, in convert
AttributeError: 'NoneType' object has no attribute 'update'
```

Version: SWMM MTP6r1 and latest branch of dev-ui-py3qt5.

**Comment by PaulDudaRESPEC** [comment]
@barrc I just committed a change that fixes this issue -- please verify and close as appropriate.

**Comment by barrc** [comment]
@PaulDudaRESPEC looks good to me, so I'll close.
